site_name: X140Yu's notes
theme: 'material'
pages:
  - Home: index.md
  - Swift:
    - 'ReactiveSwift': 'swift/reactive-swift.md'
    - 'FRP in Swift': 'swift/frp-in-swift.md'
    - 'Memory management': 'swift/memory-management.md'
