site_name: X140Yu's notes
theme: 'material'
markdown_extensions:
  - codehilite(linenums=true)
extra:
  social:
    - type: 'github'
      link: 'https://github.com/x140yu'
pages:
  - Home: index.md
  - Read:
    - 'Effective Objective-C': 'read/effective-objc.md'
  - iOS:
    - 'Xcode': 'ios/xcode.md'
    - 'ViewController': 'ios/viewController.md'
    - 'Lock': 'ios/lock.md'
    - 'Mix': 'ios/mix.md'
  - Swift:
    - 'FRP basics': 'swift/frp-in-swift.md'
    - 'RxSwift': 'swift/rxswift.md'
    - 'Memory management': 'swift/memory-management.md'
    - 'Swift and Objective-C': 'swift/swift-and-objc.md'
    - '奇技淫巧': 'swift/magic-in-swift.md'
  - FrontEnd:
    - 'HTML': 'fe/01-HTML-Basics.md'
    - 'CSS': 'fe/02-CSS-Basics.md'
